[package]
name = "password"
description = "Secure password generator. Part of the Vitamin-C cryptographic suite."
documentation = "https://docs.rs/vitaminc-password"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vitaminc-random = { path = "../random" }
vitaminc-protected = { path = "../protected" }
