[package]
name = "vitaminc-permutation"
version = "0.1.0"
edition = "2021"

[dependencies]
vitaminc-protected = { path = "../protected", features = ["bitvec"] }
vitaminc-random = { path = "../random" }

bitvec = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
paste = "1.0.15"
