[workspace]
resolver = "2"
members = [
    "packages/aead",
    "packages/aead-derive",
    "packages/aead-napi",
    "packages/aead-value",
    "packages/async-traits",
    "packages/encrypt",
    "packages/kms",
    "packages/protected",
    "packages/protected-derive",
    "packages/password",
    "packages/permutation",
    "packages/prf",
    "packages/hmac",
    "packages/random",
    "packages/random-derives",
    "packages/traits",
    "packages/vitaminc",
]

[workspace.package]
documentation = "https://docs.rs/vitaminc"
version = "0.2.0-pre.1"
repository = "https://github.com/cipherstash/vitaminc"
authors = [
  "Dan Draper <dan@cipherstash.com>",
]
edition = "2021"
rust-version = "1.85.0"
homepage = "https://cipherstash.com"
license = "MIT"
keywords = ["cryptography", "security"]
categories = ["cryptography"]

[workspace.dependencies]
bitvec = "1.0.1"
rand = { version = "0.10.1", features = ["chacha"] }
thiserror = "2.0.18"
zeroize = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
