[workspace]
resolver = "2"

members = [
    "packages/protected",
    "packages/password",
    "packages/random",
    #"packages/safe_eq",
]

[workspace.dependencies]
thiserror = "1.0.57"
zeroize = "1.7.0"
