[workspace]
resolver = "2"

members = [
    "packages/protected",
    "packages/password",
    "packages/permutation",
    "packages/random",
]

[workspace.dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
thiserror = "1.0.63"
zeroize = "1.7.0"
