use super::{Binding, BindingSupport, IndexKeyProvider, KeyProvider};
use crate::{GeneratedDataKey, IndexKeyMaterial, KeyId, KeyIsolation, KeyReconstruction};
use std::collections::HashMap;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Mutex, MutexGuard, PoisonError};
use thiserror::Error;
use vitaminc_protected::Protected;
use vitaminc_random::{Generatable, SafeRand};

/// Keys remembered under `(key_id, binding)`.
type Keys<const N: usize> = HashMap<(KeyId, Vec<u8>), Protected<[u8; N]>>;

/// An in-memory [`KeyProvider`] and [`IndexKeyProvider`] for tests and
/// examples that need generate → retrieve to round-trip without a backend.
///
/// `generate_keys` hands out a random key and a random 16-byte [`KeyId`]
/// per binding and remembers the key under `(key_id, binding)`.
/// `retrieve_keys` looks each pair up: a known id under a different binding
/// is [`FakeKeyProviderError::BindingMismatch`], an unknown id is
/// [`FakeKeyProviderError::UnknownKey`]. That is the whole contract, and it
/// is why the fake reports `BINDING = Bound`: a consumer's tests can prove
/// they present the same binding on both sides.
///
/// The index key is fixed at construction and identical across instances
/// built with [`new`](Self::new), so terms derived by one cipher match terms
/// derived by another, and known-answer tests can pin bytes. Use
/// [`with_index_key`](Self::with_index_key) to model a second keyset.
///
/// It models no backend's authorization, auditing or reconstruction
/// semantics. Counters record how many batch calls were made, for tests
/// that assert batching.
#[derive(Debug)]
pub struct FakeKeyProvider<const N: usize> {
    keys: Mutex<Keys<N>>,
    index_key: Protected<[u8; N]>,
    generate_calls: AtomicUsize,
    retrieve_calls: AtomicUsize,
}

#[derive(Debug, Error)]
pub enum FakeKeyProviderError {
    /// `position` is the request's place in the batch.
    #[error("no key with the id at batch position {position} was generated by this provider")]
    UnknownKey { position: usize },
    /// `position` is the request's place in the batch.
    #[error("the key at batch position {position} was generated under a different binding")]
    BindingMismatch { position: usize },
    #[error(transparent)]
    Random(#[from] vitaminc_random::RandomError),
}

impl<const N: usize> Default for FakeKeyProvider<N> {
    fn default() -> Self {
        Self::new()
    }
}

impl<const N: usize> FakeKeyProvider<N> {
    /// A provider with the shared default index key.
    pub fn new() -> Self {
        let mut index_key = [0u8; N];
        for (i, byte) in index_key.iter_mut().enumerate() {
            *byte = (i as u8).wrapping_mul(37) ^ 0xA5;
        }
        Self::with_index_key(Protected::new(index_key))
    }

    /// A provider with its own index key, to stand in for a different
    /// keyset than [`new`](Self::new) does.
    pub fn with_index_key(index_key: Protected<[u8; N]>) -> Self {
        Self {
            keys: Mutex::new(HashMap::new()),
            index_key,
            generate_calls: AtomicUsize::new(0),
            retrieve_calls: AtomicUsize::new(0),
        }
    }

    /// Number of keys generated so far and available to retrieve.
    pub fn len(&self) -> usize {
        self.lock().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Number of `generate_keys` batch calls so far.
    pub fn generate_calls(&self) -> usize {
        self.generate_calls.load(Ordering::SeqCst)
    }

    /// Number of `retrieve_keys` batch calls so far.
    pub fn retrieve_calls(&self) -> usize {
        self.retrieve_calls.load(Ordering::SeqCst)
    }

    /// A poisoned lock only means another test thread panicked mid-insert;
    /// the map is still a valid map.
    fn lock(&self) -> MutexGuard<'_, Keys<N>> {
        self.keys.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

impl<const N: usize> KeyProvider<N> for FakeKeyProvider<N> {
    type Error = FakeKeyProviderError;

    const RECONSTRUCTION: KeyReconstruction = KeyReconstruction::ServerOnly;
    const ISOLATION: KeyIsolation = KeyIsolation::PerValue;
    const BINDING: BindingSupport = BindingSupport::Bound;

    async fn generate_keys(
        &self,
        bindings: &[Binding<'_>],
    ) -> Result<Vec<GeneratedDataKey<N>>, Self::Error> {
        self.generate_calls.fetch_add(1, Ordering::SeqCst);
        let mut rng = SafeRand::from_entropy()?;
        let mut out = Vec::with_capacity(bindings.len());
        let mut keys = self.lock();
        for binding in bindings {
            let plaintext: Protected<[u8; N]> = Protected::new(<[u8; N]>::random(&mut rng)?);
            let key_id = KeyId::new(<[u8; 16]>::random(&mut rng)?.to_vec());
            keys.insert(
                (key_id.clone(), binding.as_bytes().to_vec()),
                plaintext.clone(),
            );
            out.push(GeneratedDataKey { plaintext, key_id });
        }
        Ok(out)
    }

    async fn retrieve_keys(
        &self,
        requests: &[(KeyId, Binding<'_>)],
    ) -> Result<Vec<Protected<[u8; N]>>, Self::Error> {
        self.retrieve_calls.fetch_add(1, Ordering::SeqCst);
        let keys = self.lock();
        requests
            .iter()
            .enumerate()
            .map(|(position, (key_id, binding))| {
                match keys.get(&(key_id.clone(), binding.as_bytes().to_vec())) {
                    Some(key) => Ok(key.clone()),
                    None if keys.keys().any(|(id, _)| id == key_id) => {
                        Err(FakeKeyProviderError::BindingMismatch { position })
                    }
                    None => Err(FakeKeyProviderError::UnknownKey { position }),
                }
            })
            .collect()
    }
}

impl<const N: usize> IndexKeyProvider<N> for FakeKeyProvider<N> {
    type Error = FakeKeyProviderError;

    async fn load_index_key(&self) -> Result<IndexKeyMaterial<N>, Self::Error> {
        Ok(IndexKeyMaterial(self.index_key.clone()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use vitaminc_protected::Controlled;

    #[tokio::test]
    async fn generate_then_retrieve_round_trips_under_the_same_binding() {
        let fake = FakeKeyProvider::<32>::new();
        let keys = fake
            .generate_keys(&[Binding::from("users/email"), Binding::from("users/age")])
            .await
            .unwrap();
        assert_eq!(keys.len(), 2);
        assert_ne!(keys[0].key_id, keys[1].key_id);

        let retrieved = fake
            .retrieve_keys(&[
                (keys[1].key_id.clone(), Binding::from("users/age")),
                (keys[0].key_id.clone(), Binding::from("users/email")),
            ])
            .await
            .unwrap();
        assert_eq!(
            retrieved[0].clone().risky_unwrap(),
            keys[1].plaintext.clone().risky_unwrap()
        );
        assert_eq!(fake.generate_calls(), 1);
        assert_eq!(fake.retrieve_calls(), 1);
    }

    #[tokio::test]
    async fn a_different_binding_is_refused() {
        let fake = FakeKeyProvider::<32>::new();
        let keys = fake.generate_keys(&[Binding::from("a")]).await.unwrap();

        let err = fake
            .retrieve_keys(&[(keys[0].key_id.clone(), Binding::from("b"))])
            .await
            .unwrap_err();
        assert!(matches!(
            err,
            FakeKeyProviderError::BindingMismatch { position: 0 }
        ));

        let err = fake
            .retrieve_keys(&[(KeyId::new(vec![0; 16]), Binding::from("a"))])
            .await
            .unwrap_err();
        assert!(matches!(
            err,
            FakeKeyProviderError::UnknownKey { position: 0 }
        ));
    }

    #[tokio::test]
    async fn two_default_fakes_share_an_index_key_and_two_keysets_do_not() {
        let a = FakeKeyProvider::<32>::new();
        let b = FakeKeyProvider::<32>::new();
        let c = FakeKeyProvider::<32>::with_index_key(Protected::new([1u8; 32]));
        let ka = a.load_index_key().await.unwrap().0.risky_unwrap();
        let kb = b.load_index_key().await.unwrap().0.risky_unwrap();
        let kc = c.load_index_key().await.unwrap().0.risky_unwrap();
        assert_eq!(ka, kb);
        assert_ne!(ka, kc);
    }
}
