//! [`KeyProvider`] impls for every vendor data key source in this crate.
//!
//! One concrete impl per source, generated by two macros, rather than one
//! blanket impl over the capability traits: those traits are plain
//! `async fn` with no `Send` bound (CIP-3986), so generic code can never
//! prove the [`MaybeSend`](super::MaybeSend) bound the provider trait
//! requires for an *arbitrary* `T`, even though every real implementation's
//! future is `Send` in practice. A concrete impl lets the compiler see the
//! monomorphised future and verify it. No `where` bound on the impls either,
//! for the same reason.
//!
//! Every constant is forwarded from the capability traits, including
//! `BINDING` — which source honours its [`Binding`](super::Binding) is the
//! source's own business, declared on its `RetrieveDataKey` impl, not a
//! property of this adapter.

#![cfg(any(feature = "aws", feature = "azure", feature = "gcp", feature = "vault"))]

use super::{Binding, BindingSupport, KeyProvider};
use crate::{
    BatchGenerateDataKey, BatchRetrieveDataKey, GenerateDataKey, GeneratedDataKey, KeyId,
    KeyIsolation, KeyReconstruction, RetrieveDataKey,
};
use vitaminc_protected::Protected;

macro_rules! key_provider_body {
    ($n:tt) => {
        type Error = <Self as GenerateDataKey<$n>>::Error;

        const RECONSTRUCTION: KeyReconstruction = <Self as RetrieveDataKey<$n>>::RECONSTRUCTION;
        const ISOLATION: KeyIsolation = <Self as BatchGenerateDataKey<$n>>::ISOLATION;
        const BINDING: BindingSupport = <Self as RetrieveDataKey<$n>>::BINDING;

        async fn generate_keys(
            &self,
            bindings: &[Binding<'_>],
        ) -> Result<Vec<GeneratedDataKey<$n>>, Self::Error> {
            BatchGenerateDataKey::generate_data_keys(self, bindings).await
        }

        async fn retrieve_keys(
            &self,
            keys: &[(KeyId, Binding<'_>)],
        ) -> Result<Vec<Protected<[u8; $n]>>, Self::Error> {
            BatchRetrieveDataKey::retrieve_data_keys(self, keys).await
        }
    };
}

/// Sources whose batch impls exist for every `N`.
macro_rules! impl_key_provider_for_any_n {
    ($($(#[$meta:meta])* $source:ty),+ $(,)?) => {
        $(
            $(#[$meta])*
            impl<const N: usize> KeyProvider<N> for $source {
                key_provider_body!(N);
            }
        )+
    };
}

/// Sources that seal `N` to a few sizes: one impl per size.
macro_rules! impl_key_provider_for_size {
    ($($(#[$meta:meta])* $source:ty => $n:literal),+ $(,)?) => {
        $(
            $(#[$meta])*
            impl KeyProvider<$n> for $source {
                key_provider_body!($n);
            }
        )+
    };
}

impl_key_provider_for_any_n! {
    #[cfg(feature = "aws")]
    crate::aws::AwsDataKeySource<N>,
    #[cfg(feature = "aws")]
    crate::aws::AwsPooledDataKeySource<N>,
    #[cfg(feature = "azure")]
    crate::azure::AzureDataKeySource<N>,
    #[cfg(feature = "azure")]
    crate::azure::AzurePooledDataKeySource<N>,
    #[cfg(feature = "gcp")]
    crate::gcp::GcpDataKeySource<N>,
    #[cfg(feature = "gcp")]
    crate::gcp::GcpPooledDataKeySource<N>,
}

// Vault accepts only 128-, 256- and 512-bit data keys, so its source seals
// `N` to those sizes. It batches natively at per-value isolation, so there
// is no pooled Vault source.
impl_key_provider_for_size! {
    #[cfg(feature = "vault")]
    crate::vault::VaultDataKeySource<16> => 16,
    #[cfg(feature = "vault")]
    crate::vault::VaultDataKeySource<32> => 32,
    #[cfg(feature = "vault")]
    crate::vault::VaultDataKeySource<64> => 64,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `BINDING` is the one capability constant a caller acts on before it
    /// trusts a backend with a context, so each source's value is pinned
    /// here rather than left to whatever the forwarding happens to produce.
    /// Two of the four cannot bind, for reasons recorded on their
    /// `RetrieveDataKey` impls — that is a documented limit, not an
    /// oversight, and this test is where it is visible side by side.
    #[test]
    fn every_source_declares_the_binding_support_it_actually_has() {
        #[cfg(feature = "aws")]
        {
            // AWS KMS binds an `EncryptionContext`.
            assert_eq!(
                <crate::aws::AwsDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Bound
            );
            // Pooling gives up binding whatever the inner source supports:
            // one key cannot carry a batch's several bindings.
            assert_eq!(
                <crate::aws::AwsPooledDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Unbound
            );
        }
        #[cfg(feature = "gcp")]
        {
            // Google Cloud KMS binds additional authenticated data.
            assert_eq!(
                <crate::gcp::GcpDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Bound
            );
            assert_eq!(
                <crate::gcp::GcpPooledDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Unbound
            );
        }
        #[cfg(feature = "azure")]
        {
            // `wrapKey`/`unwrapKey` take RSA-OAEP or AES-KW; neither has a
            // place for additional authenticated data.
            assert_eq!(
                <crate::azure::AzureDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Unbound
            );
            assert_eq!(
                <crate::azure::AzurePooledDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Unbound
            );
        }
        #[cfg(feature = "vault")]
        {
            // Transit's derivation context exists only on a `derived=true`
            // key, which this source does not require.
            assert_eq!(
                <crate::vault::VaultDataKeySource<32> as KeyProvider<32>>::BINDING,
                BindingSupport::Unbound
            );
        }
    }
}
