[package]
name = "vitaminc-random"
description = "Secure Random Number Generation. Part of the Vitamin-C cryptographic suite."
documentation = "https://docs.rs/vitaminc-random"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_chacha = "0.3.1"
rand = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }

vitaminc-protected = { version = "0.1.0-pre", path = "../protected" }
