runs:
  using: composite
  steps:

    - name: Setup Rust 1.78
      uses: dtolnay/rust-toolchain@1.78.0
      with:
        components: clippy, rustfmt

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
       cache-provider: ${{ inputs.provider }}
       shared-key: ${{ inputs.key }}
