[package]
name = "vitaminc-protected"
description = "Protected type wrappers for handling sensitive data. Part of the VitaminC cryptographic suite."
documentation = "https://docs.rs/vitaminc-protected"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { workspace = true }

digest = "0.10.7"
opaque-debug = "0.3.1"
serde = "1"
subtle = "2.6.1"
zeroize = { version = "1.8.1", features = [ "derive" ] }

[dev-dependencies]
bincode = "1.3.3"
sha2 = "0.10.8"

[features]
bitvec = []
