[package]
name = "vitaminc-protected"
description = "Protected type wrappers for handling sensitive data. Part of the VitaminC cryptographic suite."
documentation = "https://docs.rs/vitaminc-protected"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
zeroize = { workspace = true }

digest = "0.10.7"
opaque-debug = "0.3.1"
subtle = "2.6.1"

[dev-dependencies]
bincode = "1.3.3"
sha2 = "0.10.8"
serde_json = "1.0.128"

[features]
bitvec = []
