[package]
name = "protected"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.7"
opaque-debug = "0.3.1"
serde = { version = "1.0.197", features = ["derive"] }
serdect = "0.2.0"
subtle = "2.5.0"
zeroize = { version = "1.6.0", features = [ "derive" ] }

[dev-dependencies]
bincode = "1.3.3"
sha2 = "0.10.8"
