[package]
name = "vitaminc-protected"
version = "0.1.0-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { workspace = true }

digest = "0.10.7"
opaque-debug = "0.3.1"
serde = "1.0.208"
subtle = "2.6.1"
zeroize = { version = "1.8.1", features = [ "derive" ] }

[dev-dependencies]
bincode = "1.3.3"
sha2 = "0.10.8"

[features]
bitvec = []
