[package]
name = "vitaminc-async-traits"
description = "Vitamin C async traits"
documentation = "https://docs.rs/vitaminc-async-traits"
version.workspace = true
repository.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version = "1.75.0"

[dependencies]
vitaminc-protected = { version = "0.1.0-pre", path = "../protected" }
vitaminc-traits = { version = "0.1.0-pre", path = "../traits" }
