[package]
name = "vitaminc-traits"
description = "Vitamin C traits"
documentation.workspace = true
version.workspace = true
repository.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version = "1.61.0"

[dependencies]
vitaminc-protected = { version = "0.1.0-pre", path = "../protected" }

