[package]
name = "vitaminc-traits"
description = "Vitamin C traits"
documentation = "https://docs.rs/vitaminc-traits"
version.workspace = true
repository.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version = "1.61.0"

[dependencies]
rmp-serde = "1.3.0"
vitaminc-protected = { version = "0.1.0-pre", path = "../protected" }
vitaminc-random = { version = "0.1.0-pre", path = "../random" }

serde = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
bytes = { version = "^1", features = ["serde"] }
anyhow = "1"

